apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':reactive-web')
    implementation project(':model')
    implementation project(':usecase')
    implementation project(':r2dbc-postgresql')
    implementation project(':kafka-consumer')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.kafka:spring-kafka'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'tools.jackson.core:jackson-databind'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = "${rootProject.name}.${archiveExtension.get()}"
}
