dependencies {
    implementation project(':model')
    implementation project(':usecase')

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'tools.jackson.core:jackson-databind'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
}
