server:
  port: 8081
spring:
  application:
    name: "ms-catalog"
  devtools:
    add-properties: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/arka_catalog}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ms-catalog
      auto-offset-reset: earliest
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
arka:
  catalog:
    use-in-memory-repository: true   # cambia a false cuando MongoDB esté arriba
    use-in-memory-broker: true       # cambia a false cuando Kafka esté arriba
